sudo: required

services: docker

env:
  matrix:
    - LOCO_VERSION=v3.4.x-2018113002 WAGON_VERSION=v3.4.x-20181115

before_install:
  - sudo pip install docky
  - ./travis/install

script:
  - docker build --no-cache -t current-latest --build-arg version=$LOCO_VERSION demo

after_success:
- ./travis/publish
